---
# Source: showks-aggregator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-aggregator
  labels:
    app: showks-aggregator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: app-port
  selector:
    app: showks-aggregator

---
# Source: showks-aggregator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-aggregator
  labels:
    app: showks-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-aggregator
  template:
    metadata:
      labels:
        app: showks-aggregator
    spec:
      containers:
        - name: showks-aggregator
          image: containerdaysjp/showks-aggregator:stg-4e7a4687f61c163ec21adc14d0bddce1e14b2ef9
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP

