apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.userID }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.userID }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: app-port
  selector:
    app: {{ .Chart.Name }}-{{ .Values.userID }}

