apiVersion: v1
kind: Service
metadata:
  name: showks-webapp-{{ .Values.userInfo.userName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: showks-webapp-{{ .Values.userInfo.userName }}
    helm.sh/chart: {{ include "showks-webapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: showks-webapp-{{ .Values.userInfo.userName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
