---
# Source: showks-canvas/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-canvas-
  namespace: showks
  labels:
    app: showks-canvas
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: app-port
  selector:
    app: showks-canvas


---
# Source: showks-canvas/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-canvas-
  namespace: showks
  labels:
    app: showks-canvas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-canvas
  template:
    metadata:
      labels:
        app: showks-canvas
    spec:
      containers:
        - name: showks-canvas-
          image: containerdaysjp/showks-canvas-:prod-c916c589695d6a564eb117b9ab50d14f4b8a8e3a
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP

