apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: showks-portal
  namespace: showks-portal
  labels:
    source: test
    stack: portal
    app: showks-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      source: test
      app: showks-portal
  template:
    metadata:
      labels:
        source: test
        app: showks-portal
    spec:
      containers:
      - name: primary
        image: containerdaysjp/showks-portal
        ports:
        - containerPort: 3000
