---
# Source: showks-portal/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-portal
  namespace: showks
  labels:
    app: showks-portal
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: app-port
  selector:
    app: showks-portal

---
# Source: showks-portal/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-portal
  namespace: showks
  labels:
    app: showks-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-portal
  template:
    metadata:
      labels:
        app: showks-portal
    spec:
      containers:
        - name: showks-portal
          image: containerdaysjp/showks-portal:stg-105423cc57994e9c652e6169066a8add1017fc4d
          ports:
            - name: app-port
              containerPort: 3000
              protocol: TCP

---
# Source: showks-portal/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: showks-portal
  namespace: showks
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: portal.stg.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-portal
          servicePort: 3000

