apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: showks
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: app-port
  selector:
    app: {{ .Chart.Name }}
